dist: trusty
sudo: required
language: bash
before_install:
- echo "hello world"
notifications:
  slack:
    secure: j/gOyABMe61sLMcXt28lJSXbpfAo5DMFJkXP+myCvKmipghxTUmUl9ABp/n/47/kD1uCB/3QNRjYIoktfWwNT7Ztvh6NAdsHTGXBoy+wjGjWQZ/Bozq0K3mn3XgO0qrqAi1Koto9S2vwkYSF9MixTelK2eoflxMzTKNjXt5ZzxEUYHyi7xxikByWmgOmvI7cr2twOJ1tBKlBpnfG+WoBsX1WRC2vO8LhXqqZFOjx9iDvjWRXQAWs9cMK81rkXVnnI8N6vD45BEPeAaFMWAU+pB8Hmy1W1OwABmRbpbEz1GFGpHzmWEKFERf/xps0aS59jCLFCdS32BdJMKJLGuyEYp0zgqcCf2AtnHnzLXqwvQ4oyt81/VmGLtL50zOZHMFqW2PXZkRytAlxPwkf0ns7NIS/Hk8bz4FQX1vCMN5wUhRk9d+ueAyvdMxiJvskMTqiNCQURSwfmWn/XNlGw1177iFNSzteI6klWsIYoVvoxCT8t3faug+yBiAL6Y6L+YcBwZseBBlcdxW07jvVsP9DLTsiHTzxOBSPUDX3Gm2LCKteXvlieNV4XBW67I2+Z52L0QKaM7+E1LXdykxT6x1Z0RjbFzeHF9Z4fOVopaqdLVzYGodTQvtbdmXu7KT4OTpK6x29AoMtgkr253qOLTB0ZJN9L9oCuu8u08cX1fn11XI=
