dist: trusty
sudo: required
language: bash
before_install:
- echo "hello world"
notifications:
  slack:
    secure: MnwMvEV8xuVyxFswhVFcnwGIZ7ys0X6MmSqlB7gwSblum02RyMtIDiBX8DhBe/ohRg0vI1UMpw3cBf/xaoSyHGDvDIDCuQn7UyZLv29pFft3kCB72jhfR8WjSTf3c5uFRBJt3TFcFL+JhSopiURAkbjO87bHpPhjgILdcG7PNLcPaipwstDFGraG3614mi4vDTm2sz3f9N7MgZXk3vs1rskMvlISNhY2Lv9nt8KOA/YCEZd2oYYJCvlzbuc32gSUjAbqnXXfyTX8J16aGSzIJh/WRaJB3/3n6yOR3UuSyVHCa9WA1ErzTu+/NlW25fkGt013qSpEj0OBGiRaTSykCBfJLW5YRvZEcvhXJapeWewa/Ncue5CxVOQC063lge/pyvFDjAba7s2DdyScY6i0JWR8L78uokB3cc8I4zRiCgzvcw+wtly8oCcywQkU7vHzjw6bXtthxUCD6QOVsFOOKkYQFLBPK7NW3hTrTNaZoJgTD0AW7u7ZVWW8SdK3GgMpwDQ3vuA1mFZIXvRqNaqv+AIP4Zwyni2rDiLCaDMe7f8V5FCsKpnLypD8eLxblpJqCqK+d7nHCc8ch8Z38GM7T/bQlcIOMbzA4/oSBVhMTNppr8w5VaWg0PkD/pO+YGMX21d/hEzys/EYtsNEm0dj0dPSf56Buw5GwJ7R9Wz6C34=
